package com.audioagent.contentanalysis.validation;

public enum AnalysisResultValidationErrorCode {
    JSON_PARSE_FAILED,
    RESULT_VALIDATION_FAILED,
    REPAIR_JSON_PARSE_FAILED,
    REPAIR_RESULT_VALIDATION_FAILED,
    MISSING_SUMMARY,
    NULL_ARRAY,
    NULL_ARRAY_ITEM,
    INVALID_ORDER,
    DUPLICATE_ORDER,
    MISSING_EVIDENCE_CHUNK_IDS,
    UNKNOWN_CHUNK_ID,
    MISSING_EVIDENCE_QUOTE,
    EVIDENCE_QUOTE_TOO_LONG,
    EVIDENCE_QUOTE_NOT_FOUND,
    INVALID_ISSUE_TYPE,
    INVALID_SEVERITY,
    CHAPTER_RANGE_REVERSED,
    CHAPTER_ORDER_REVERSED
}
